##############################    tema utilizado en plotNyquist()   #########################################
theme_at <- function(base_size = 16, base_family = "",
                     base_line_size = base_size/12,
                     base_rect_size = base_size/12,
                     half_line = base_size/2){

  t <- ggplot2::theme(line = ggplot2::element_line(colour = "black", size = base_line_size, linetype = 1, lineend = "butt"),
                      rect = ggplot2::element_rect(fill = "white", colour = "black", size = base_rect_size, linetype = 1),
                      text = ggplot2::element_text(family = base_family, face = "plain", colour = "black", size = base_size,
                                                   lineheight = 0.9, hjust = 0.5, vjust = 0.5, angle = 0, margin = ggplot2::margin(),
                                                   debug = FALSE),

                      axis.line = ggplot2::element_blank(),
                      axis.line.x = NULL,
                      axis.line.y = NULL,
                      axis.text = ggplot2::element_text(size = ggplot2::rel(1.2), colour = "black"),
                      axis.text.x = ggplot2::element_text(margin = ggplot2::margin(t = 0.8*half_line/2), vjust = 1, hjust = 0.7, colour = "black"),
                      axis.text.x.top = ggplot2::element_text(margin = ggplot2::margin(b = 0.8 * half_line / 2), vjust = 0),
                      axis.text.y = ggplot2::element_text(margin = ggplot2::margin(r = 0.8*half_line/2), hjust = 1, vjust = 0.7, colour = "black"),
                      axis.text.y.right = ggplot2::element_text(margin = ggplot2::margin(l = 0.8 * half_line / 2), hjust = 0),
                      axis.ticks = ggplot2::element_line(colour = "black"),
                      axis.ticks.length = ggplot2::unit(half_line / 2, "pt"),
                      axis.ticks.length.x = NULL,
                      axis.ticks.length.x.top = NULL,
                      axis.ticks.length.x.bottom = NULL,
                      axis.ticks.length.y = NULL,
                      axis.ticks.length.y.left = NULL,
                      axis.ticks.length.y.right = NULL,
                      axis.title.x = ggplot2::element_text(size = ggplot2::rel(1.4), margin = ggplot2::margin(t = half_line/2), vjust = -0.5, color = "black", face="bold"),
                      axis.title.x.top = ggplot2::element_text(margin = ggplot2::margin(b = half_line/2), vjust = 0),
                      axis.title.y = ggplot2::element_text(size = ggplot2::rel(1.4), angle = 90, margin = ggplot2::margin(r = half_line/2), vjust = 1.5, color = "black", face="bold"),
                      axis.title.y.right = ggplot2::element_text(angle = -90, margin = ggplot2::margin(l = half_line/2), vjust = 0),

                      legend.background = ggplot2::element_rect(colour = NA),
                      legend.spacing = ggplot2::unit(2*half_line, "pt"),
                      legend.spacing.x = NULL,
                      legend.spacing.y = NULL,
                      legend.margin = ggplot2::margin(0, 0, 0, 0, "cm"),
                      legend.key = ggplot2::element_rect(fill = "white", colour=NA),
                      legend.key.size = ggplot2::unit(1.2, "lines"),
                      legend.key.height = NULL,
                      legend.key.width = NULL,
                      legend.text = ggplot2::element_text(size = ggplot2::rel(1.3), vjust = 1.5),
                      legend.text.align = NULL,
                      legend.title = ggplot2::element_text(size = ggplot2::rel(1.3), hjust = 0),
                      legend.title.align = NULL,
                      legend.position = "right",
                      legend.direction = NULL,
                      legend.justification = "center",
                      legend.box = NULL,
                      legend.box.margin = ggplot2::margin(0, 0, 0, 0, "cm"),
                      legend.box.background = ggplot2::element_blank(),
                      legend.box.spacing = ggplot2::unit(2*half_line, "pt"),

                      panel.background = ggplot2::element_rect(fill = "white", colour = NA),
                      panel.border = ggplot2::element_rect(fill = NA, colour = "black"),
                      panel.grid.major = ggplot2::element_blank(),
                      panel.grid.minor = ggplot2::element_blank(),
                      panel.spacing = ggplot2::unit(half_line, "pt"),
                      panel.spacing.x = NULL,
                      panel.spacing.y = NULL,
                      panel.ontop =  FALSE,

                      strip.background = ggplot2::element_rect(fill = "grey85", colour = "grey20"),
                      strip.text = ggplot2::element_text(colour = "black", size = ggplot2::rel(0.8),
                                                         margin = ggplot2::margin(0.8*half_line, 0.8*half_line, 0.8*half_line, 0.8*half_line)),
                      strip.text.x = NULL,
                      strip.text.y = ggplot2::element_text(angle = -90),
                      strip.placement = "inside",
                      strip.placement.x = NULL,
                      strip.placement.y = NULL,
                      strip.switch.pad.grid = ggplot2::unit(half_line/2, "pt"),
                      strip.switch.pad.wrap = ggplot2::unit(half_line/2, "pt"),

                      plot.background = ggplot2::element_rect(colour = "white"),
                      plot.title = ggplot2::element_text(size = ggplot2::rel(2), hjust = 0, vjust = 2, face = "bold.italic",
                                                         color = "black", lineheight = 1.5, margin = ggplot2::margin(b = half_line)),
                      plot.margin = ggplot2::margin(half_line, half_line, half_line, half_line),

                      complete = TRUE
  )
}
